version = 1

[[annotations]]
path = ["package.json", "CHANGELOG.md", ".gitignore", "docs/CNAME"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "hexagenapp/android/**",
  "hexagenapp/ios/**",
  "hexagenapp/linux/**",
  "hexagenapp/web/**",
  "hexagenapp/windows/**",
  "hexagenapp/macos/**",
  "hexagenapp/.gitignore",
  "hexagenapp/.metadata",
  "hexagenapp/test/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/ISSUE_TEMPLATE/**", ".github/PULL_REQUEST_TEMPLATE.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"
