version = 1

[[annotations]]
path = [
  "package.json",
  "CHANGELOG.md",
  "**/.gitignore",
  "docs/CNAME",
  ".husky/**",
  "package-lock.json",
  "pnpm-lock.yaml",
  "**/.metadata",
  "**/l10n/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "hexagenapp/android/**",
  "hexagenapp/ios/**",
  "hexagenapp/web/**",
  "hexagenapp/macos/**",
  "hexagenapp/windows/**",
  "hexagenapp/linux/**",
  "hexagenapp/assets/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/ISSUE_TEMPLATE/**", ".github/PULL_REQUEST_TEMPLATE.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"
