# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

name: Deploy Flutter to Google Play (Internal)

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: "Release name (Play Console notu)"
        required: false
        default: "CI Internal"
      track:
        description: "Play track (internal/alpha/beta/production)"
        required: true
        default: "internal"
      status:
        description: "Release status (draft/inProgress/halted/completed)"
        required: true
        default: "completed"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hexagenapp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"

      - name: Flutter pub get
        run: flutter pub get

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # --- Build number'ı otomatik artır ---
      # Base'i 10000 seçtik; ilk koşu 10001 olur. İstersen aşağıdaki 10000 değerini değiştir.
      - name: Derive BUILD_NUMBER from run_number
        run: |
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}"
          echo "BUILD_NUMBER=$((10000 + GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Update pubspec.yaml (+BUILD_NUMBER)
        run: |
          BN="${BUILD_NUMBER}"
          if grep -qE '^version: [0-9]+\.[0-9]+\.[0-9]+\+[0-9]+' pubspec.yaml; then
            sed -i -E "s/^version: ([0-9]+\.[0-9]+\.[0-9]+)\+[0-9]+$/version: \1+${BN}/" pubspec.yaml
          else
            # version satırı yoksa bir default ekleyelim
            echo "" >> pubspec.yaml
            echo "version: 1.0.0+${BN}" >> pubspec.yaml
          fi
          echo "pubspec version -> $(grep '^version:' pubspec.yaml)"

      # --- İmzalama ayarlarını hazırla ---
      - name: Prepare signing (keystore & key.properties)
        run: |
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=app/upload-keystore.jks
          EOF

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Build AAB (release)
        run: flutter build appbundle --release
