# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

name: 🤖 Lint & Format

on:
  pull_request:
    branches:
      - develop
      - main
      - "release/**"

env:
  PROJECT_DIR: hexagenapp

jobs:
  lint:
    name: Check Formatting (hexaGenApp)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (required by some Flutter tooling)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Cache Pub & .dart_tool
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ env.PROJECT_DIR }}/.dart_tool
          key: pub-${{ runner.os }}-${{ hashFiles(format('{0}/pubspec.lock', env.PROJECT_DIR)) }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: flutter pub get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Check formatting
        working-directory: ${{ env.PROJECT_DIR }}
        run: dart format --output=none --set-exit-if-changed .

      - name: Static analysis
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter analyze
