# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

name: iOS → TestFlight (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest

    env:
      BUILD_NUMBER: ${{ github.run_number }} # passed to Fastlane

    steps:
      - name: Checkout (default branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install fastlane
        run: gem install fastlane

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          # flutter-version: '3.24.3'  # uncomment to pin

      # -----------------------------
      # Speed-ups: caches (optional)
      # -----------------------------
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('hexagenapp/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Cache Flutter pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('hexagenapp/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # --- Code signing: import certificate (.p12) into a temp keychain ---
      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.IOS_CERT_P12 }}
          p12-password: ${{ secrets.IOS_CERT_PASSWORD }}

      # --- Code signing: install provisioning profile (no heredoc, linter-safe) ---
      - name: Install provisioning profile
        env:
          IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          python3 -c 'import os,base64; pp=os.environ.get("IOS_PROVISIONING_PROFILE",""); open(os.path.expanduser("~/Library/MobileDevice/Provisioning Profiles/app.mobileprovision"),"wb").write(base64.b64decode(pp))'
          echo "Provisioning profile installed at: $HOME/Library/MobileDevice/Provisioning Profiles/app.mobileprovision"

      # --- CocoaPods (only if Podfile exists) ---
      - name: Install CocoaPods (inside hexagenapp/ios, if Podfile exists)
        run: |
          if [ -f "hexagenapp/ios/Podfile" ]; then
            sudo gem install cocoapods
            cd hexagenapp/ios
            pod repo update
            pod install
          else
            echo "No Podfile found under hexagenapp/ios — skipping pod install. Flutter will handle Pods during build if needed."
          fi

      # --- Configure App Store Connect API key for fastlane (no heredoc) ---
      - name: Configure App Store Connect API key (fastlane/api_key.json)
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_PRIVATE_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
        run: |
          mkdir -p fastlane
          python3 -c 'import os,json; key=os.environ["ASC_PRIVATE_KEY"].replace("\\n","\n"); open("fastlane/api_key.json","w").write(json.dumps({"key_id":os.environ["ASC_KEY_ID"],"issuer_id":os.environ["ASC_ISSUER_ID"],"key":key,"in_house":False}))'
          echo "APP_STORE_CONNECT_API_KEY_PATH=$GITHUB_WORKSPACE/fastlane/api_key.json" >> $GITHUB_ENV

      # --- Build and upload to TestFlight using Fastlane ---
      - name: Build & Upload to TestFlight
        run: fastlane ios beta

      # Artifact (optional but handy)
      - name: Upload IPA artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: hexagenapp/build/ios/ipa/*.ipa
          if-no-files-found: ignore
